### PR TITLE
Auth fix

### PR DESCRIPTION
**Pull request by nayakastha**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [X] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [X] Check the commit's or even all commits' message styles matches our requested structure.
- [X] Check your code additions will fail neither code linting checks nor unit test.

### Description
Solves the existing issues with Authentication #8 

❤️Thank you!

### Build Status
[pr-build-test](https://github.com/dscnitrourkela/project-maple/actions/workflows/pull_request.yml)

### CODE REVIEW

**Review by SriramPatibanda — CHANGES_REQUESTED** [review]
- When a wrong otp is entered, the snackbar isn't displayed and the app stays on the same page
- 
WhatsApp Image 2021-06-21 at 9 13 47 PM
When a user enters wrong data and the warnings are displayed, there's a pixel overflow and that prevents the user from accessing the proceed button

**Comment by nayakastha** [comment]
Check with 'run without debugging' for best results @SriramPatibanda

**Review by abhibhaw — APPROVED** [review]
@nayakastha op 🎉

**Review by SriramPatibanda — APPROVED** [review]

**Comment by abhibhaw** [comment]
@all-contributors please add @nayakastha for code, doc, ideas, projectManagement, maintenance

**Comment by abhibhaw** [comment]
@all-contributors please add @abhibhaw for code, doc, ideas, projectManagement, maintenance

**Comment by abhibhaw** [comment]
@all-contributors please add @SriramPatibanda for code, doc, ideas, projectManagement, maintenance

**Pull request merged**
